"""Create or update the bootstrap admin account in Supabase.

Usage:
  ADMIN_BOOTSTRAP_PASSWORD='your-password' python -m backend.scripts.create_admin_user

The password is never stored in this file or printed. The hash is generated by
backend.routers.admin.hash_password, the exact utility used by admin login.
"""
from __future__ import annotations

import argparse
import getpass
import os
import sys
from pathlib import Path

# Ensure imports resolve when invoked as a file from the repository root.
ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from supabase import create_client
from backend.config import settings
from backend.routers.admin import hash_password

DEFAULT_USERNAME = "admin"
DEFAULT_EMAIL = "amraniariel11@gmail.com"
DEFAULT_ROLE = "admin"
DEFAULT_STATUS = "active"


def provision_admin(username: str, email: str, password: str) -> dict:
    if len(password) < 8:
        raise ValueError("Password must be at least 8 characters")

    client = create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_KEY)
    password_hash = hash_password(password)
    payload = {
        "username": username,
        "email": email,
        "password_hash": password_hash,
        "role": DEFAULT_ROLE,
        "status": DEFAULT_STATUS,
        "permissions": {
            "manage_domains": True,
            "manage_abuse_reports": True,
            "view_analytics": True,
            "manage_admins": True,
        },
        "login_attempts": 0,
        "locked_until": None,
    }

    existing = client.table("admin_users").select("id").eq("email", email).limit(1).execute()
    if existing.data:
        result = client.table("admin_users").update(payload).eq("id", existing.data[0]["id"]).execute()
        action = "updated"
    else:
        result = client.table("admin_users").insert(payload).execute()
        action = "created"

    if not result.data:
        raise RuntimeError("Supabase did not return the provisioned admin record")
    return {"action": action, "id": result.data[0].get("id"), "email": email, "role": DEFAULT_ROLE, "status": DEFAULT_STATUS}


def main() -> int:
    parser = argparse.ArgumentParser(description="Create or update the ConversaPay admin user")
    parser.add_argument("--username", default=DEFAULT_USERNAME)
    parser.add_argument("--email", default=DEFAULT_EMAIL)
    parser.add_argument("--password-env", default="ADMIN_BOOTSTRAP_PASSWORD")
    args = parser.parse_args()

    password = os.getenv(args.password_env) or getpass.getpass("Admin password: ")
    try:
        result = provision_admin(args.username, args.email, password)
    except Exception as exc:
        print(f"Admin provisioning failed: {exc}", file=sys.stderr)
        return 1

    print(f"Admin {result['action']}: {result['email']} ({result['role']}, {result['status']})")
    print("Password hash generated with backend.routers.admin.hash_password and stored in Supabase.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
