const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {spawnSync}=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.join(__dirname,'..');
const fixtures=spawnSync(process.env.TEST_PYTHON||'python',[path.join(__dirname,'render_frontend_fixtures.py')],{cwd:root,encoding:'utf8',maxBuffer:4*1024*1024});
if(fixtures.status!==0)throw Error(fixtures.stderr);
const pages=JSON.parse(fixtures.stdout);
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});let count=0;
 const business={id:'b',business_name:'Existing business'};
 const defaults=endpoint=>({body:endpoint==='/businesses'?[business]:endpoint==='/auth/me'?{email:'owner@example.com',profile:{full_name:'Owner'}}:endpoint==='/profile'?{email:'owner@example.com',profile:{full_name:'Owner',phone:'123'}}:endpoint==='/products/paged'?{products:[],total:0,total_pages:0}:endpoint==='/profile/notifications'?{preferences:{payment_success:true,weekly_digest:true,security_alerts:true,product_updates:false}}:{keys:[],orders:[],plan_type:'free',sessions:[],usage:{used:2,limit:1000},limited:false}});
 async function pageFor(name,handler=async endpoint=>defaults(endpoint),{token=true,lang='he',query=''}={}){
  const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(({token,lang})=>{if(token){localStorage.setItem('access_token','offline');localStorage.setItem('user_id','offline-user')}localStorage.setItem('conversapay-language',lang)},{token,lang});
  await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.host!=='ux.test')return route.abort();if(url.pathname==='/'+name)return route.fulfill({contentType:'text/html',body:pages[name]});if(url.pathname.startsWith('/api/v1/')){const response=await handler(url.pathname.slice(7),route.request());return route.fulfill({status:response?.status||200,contentType:'application/json',body:JSON.stringify(response?.body||{})})}const file=path.join(root,url.pathname.slice(1));if(fs.existsSync(file)&&fs.statSync(file).isFile())return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':'text/css'});return route.abort()});
  await page.goto('http://ux.test/'+name+query);page.uxErrors=errors;return page;
 }
 async function done(page,label){assert.deepEqual(page.uxErrors,[],label+' has no JavaScript exceptions');count++;console.log('PASS: '+label);await page.close()}
 try{
  let p=await pageFor('dashboard',async endpoint=>endpoint==='/businesses'?{status:500}:defaults(endpoint));await p.waitForFunction(()=>document.querySelector('#notice').textContent.includes('לא ניתן לטעון'));assert.equal(await p.locator('#gate').count(),0);await done(p,'failed business load never creates an empty-business gate');
  p=await pageFor('dashboard',async endpoint=>endpoint==='/products/paged'?{status:500}:defaults(endpoint));await p.locator('#products [data-load-error]').waitFor();assert.equal(await p.locator('#products').textContent().then(text=>text.includes('אין מוצרים עדיין')),false);await done(p,'catalog failure has a retry state instead of an empty catalog');
  let notificationPayload,fail=true;
  p=await pageFor('settings',async(endpoint,request)=>{if(endpoint==='/profile/notifications'){if(request.method()==='PUT'){notificationPayload=request.postDataJSON();return{body:{preferences:notificationPayload}}}if(fail)return{status:500}}return defaults(endpoint)});
  await p.waitForFunction(()=>document.querySelector('#businessName').value==='Existing business');assert.equal(await p.locator('#notificationsForm button').isDisabled(),true);assert.equal(notificationPayload,undefined);
  fail=false;await p.locator('#toastWrap button').filter({hasText:'נסה שוב'}).click();await p.waitForFunction(()=>!document.querySelector('#notificationsForm button').disabled);assert.equal(await p.locator('#payment_success').isChecked(),true);await p.locator('#notificationsForm button').click();await p.waitForFunction(()=>document.querySelector('#toastWrap').textContent.includes('העדפות נשמרו'));assert.equal(notificationPayload.payment_success,true);await done(p,'notification load failure blocks destructive saving and retry restores real values');
  p=await pageFor('login',async()=>({status:503}),{token:false});await p.locator('#email').fill('owner@example.com');await p.locator('#password').fill('correct-password');await p.locator('#submit').click();await p.waitForFunction(()=>document.querySelector('#toastWrap').textContent.includes('השירות אינו זמין'));assert.equal((await p.locator('#toastWrap').textContent()).includes('סיסמה שגויים'),false);await done(p,'server outage is not reported as bad credentials');
  p=await pageFor('register',async()=>({status:502,body:{detail:'verification_email_failed'}}),{token:false});for(const [id,value]of Object.entries({name:'Owner',business:'Business',email:'owner@example.com',password:'test-password-123',confirm:'test-password-123'}))await p.locator('#'+id).fill(value);await p.locator('#terms').check();await p.locator('#submit').click();await p.locator('#verifyLayer.show').waitFor();assert.equal(await p.locator('#resendButton').isVisible(),true);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('#verifyLayer').classList.contains('show'));await done(p,'failed signup email exposes resend and the dialog closes with Escape');
  let release;const late=new Promise(resolve=>release=resolve);
  p=await pageFor('onboarding',async()=>{await late;return{body:{completed:false,custom_ai_instructions:'Old instructions'}}});await p.locator('.category-card').first().click();await p.locator('#toInstructions').click();await p.locator('#customInstructions').fill('New instructions');release();await p.waitForFunction(()=>document.querySelector('#loadNote').textContent.includes('נטענו'));assert.equal(await p.locator('#customInstructions').inputValue(),'New instructions');await done(p,'late onboarding data cannot overwrite new typing');
  p=await pageFor('profile',async(endpoint,request)=>endpoint.startsWith('/businesses/')?{status:500}:defaults(endpoint));await p.waitForFunction(()=>!document.querySelector('#save').disabled);await p.locator('#fullName').fill('New name');await p.locator('#businessName').fill('New business');await p.locator('#save').click();await p.waitForFunction(()=>document.querySelector('#toastWrap').textContent.includes('שמירת שם העסק נכשלה'));await done(p,'partial profile save explains which details were saved');
  p=await pageFor('success');await p.waitForFunction(()=>document.querySelector('#title').textContent.includes('לא ניתן לאמת'));assert.equal((await p.locator('#title').textContent()).includes('הושלם'),false);await done(p,'payment without a reference never claims success');
  p=await pageFor('success',async()=>({}),{token:false,query:'?session_id=cs_test'});await p.locator('a[href^="/login?next="]').waitFor();assert.equal((await p.locator('a[href^="/login?next="]').getAttribute('href')).includes('cs_test'),true);await done(p,'sign-in from payment preserves its reference');
  p=await pageFor('settings',undefined,{lang:'en'});await p.waitForFunction(()=>document.querySelector('h1').textContent==='Settings');assert.equal(await p.locator('#saveBusiness').textContent(),'Save business details');await p.evaluate(()=>{document.querySelector('#saveBusiness').textContent='נסה שוב'});await p.waitForFunction(()=>document.querySelector('#saveBusiness').textContent==='Retry');await done(p,'English settings and dynamic action text remain translated');
  p=await pageFor('dashboard');await p.waitForFunction(()=>document.querySelector('#businessName').textContent==='Existing business');await p.locator('#addProduct').click();await p.waitForFunction(()=>!document.querySelector('#productForm').hidden);await p.locator('#closeProductX').focus();await p.keyboard.press('Tab');assert.equal(await p.locator('#productForm').evaluate(el=>el.contains(document.activeElement)),true);await p.keyboard.press('Escape');await p.waitForFunction(()=>document.querySelector('#productForm').hidden);await done(p,'product dialog contains keyboard focus and supports Escape');
  p=await pageFor('product-import');assert.equal(await p.locator('#drop').evaluate(el=>el.tagName),'BUTTON');await p.locator('#drop').focus();assert.equal(await p.locator('#drop').evaluate(el=>el===document.activeElement),true);
  const parsed=await p.evaluate(()=>Talk2PayImport.parse([{name:'Missing price',sku:'A',price:''},{name:'Explicit free',sku:'B',price:'0'}],'b'));assert.equal(parsed.products.length,1);assert.equal(parsed.products[0].payload.price,0);assert.equal(parsed.errors[0].row,2);await done(p,'file chooser is keyboard accessible and blank prices are not free products');
  p=await pageFor('settings');await p.waitForFunction(()=>document.querySelector('#sessionSummary').textContent.includes('אינה זמינה'));assert.equal((await p.locator('#sessionSummary').textContent()).includes('1 סשן'),false);assert.equal(await p.locator('a[href="/upgrade#invoices"]').textContent(),'מידע על מסמכי חיוב');await done(p,'sessions and document links do not promise unavailable information');
  for(const name of ['settings','profile','product-import']){p=await pageFor(name);await p.setViewportSize({width:375,height:812});await p.waitForFunction(()=>document.readyState==='complete');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await done(p,name+' fits a 375px mobile viewport')}
  for(const name of ['settings','profile','upgrade','product-import','login','register','success','dashboard']){p=await pageFor(name,undefined,{token:!['login','register'].includes(name),lang:'en'});await p.waitForFunction(()=>document.documentElement.lang==='en');const missing=await p.evaluate(()=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),items=[];let node;while(node=walker.nextNode()){const element=node.parentElement;if(element&&!element.closest('script,style')&&element.getClientRects().length&&/[\u0590-\u05ff]/.test(node.nodeValue)&&node.nodeValue.trim()!=='עברית')items.push(node.nodeValue.trim())}return [...new Set(items)]});assert.deepEqual(missing,[],name+' visible English copy');await done(p,name+' has fully translated visible English copy')}
  console.log(`PASS: ${count} UX browser regressions`);
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
