create extension if not exists pgcrypto;

create table if not exists public.lead_submissions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 120),
  email text not null check (char_length(trim(email)) between 5 and 320),
  company text check (company is null or char_length(company) <= 160),
  message text not null check (char_length(trim(message)) between 2 and 4000),
  source text not null default 'site-builder' check (char_length(trim(source)) between 2 and 80),
  page_url text check (page_url is null or char_length(page_url) <= 2048),
  ip_address inet,
  user_agent text,
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'converted', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lead_submissions_business_created_idx on public.lead_submissions (business_id, created_at desc);
create index if not exists lead_submissions_business_status_idx on public.lead_submissions (business_id, status);

alter table public.lead_submissions enable row level security;

drop policy if exists lead_submissions_owner_select on public.lead_submissions;
drop policy if exists lead_submissions_owner_update on public.lead_submissions;
drop policy if exists lead_submissions_owner_delete on public.lead_submissions;

create policy lead_submissions_owner_select on public.lead_submissions
for select to authenticated
using (public.user_owns_business(business_id));

create policy lead_submissions_owner_update on public.lead_submissions
for update to authenticated
using (public.user_owns_business(business_id))
with check (public.user_owns_business(business_id));

create policy lead_submissions_owner_delete on public.lead_submissions
for delete to authenticated
using (public.user_owns_business(business_id));

create or replace function public.touch_lead_submissions_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lead_submissions_touch_updated_at on public.lead_submissions;
create trigger lead_submissions_touch_updated_at
before update on public.lead_submissions
for each row execute function public.touch_lead_submissions_updated_at();

create table if not exists public.site_lead_rate_limits (
  key_hash text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.site_lead_rate_limits enable row level security;
revoke all on table public.site_lead_rate_limits from anon, authenticated;
grant all on table public.site_lead_rate_limits to service_role;

create or replace function public.consume_site_lead_rate_limit(
  p_key text,
  p_limit integer default 5,
  p_window_seconds integer default 3600
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.site_lead_rate_limits%rowtype;
  now_value timestamptz := now();
begin
  if p_key is null or length(trim(p_key)) < 16 or p_limit < 1 or p_window_seconds < 1 then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtext(p_key));
  select * into current_row from public.site_lead_rate_limits where key_hash = p_key for update;

  if not found or current_row.window_started_at + make_interval(secs => p_window_seconds) <= now_value then
    insert into public.site_lead_rate_limits(key_hash, window_started_at, request_count, updated_at)
    values (p_key, now_value, 1, now_value)
    on conflict (key_hash) do update set window_started_at = excluded.window_started_at, request_count = 1, updated_at = excluded.updated_at;
    return true;
  end if;

  if current_row.request_count >= p_limit then
    return false;
  end if;

  update public.site_lead_rate_limits set request_count = request_count + 1, updated_at = now_value where key_hash = p_key;
  return true;
end;
$$;

revoke all on function public.consume_site_lead_rate_limit(text, integer, integer) from public;
grant execute on function public.consume_site_lead_rate_limit(text, integer, integer) to service_role;

comment on table public.lead_submissions is 'Inbound public lead forms generated by Site Builder pages; service role inserts, business owners read through RLS.';
comment on table public.site_lead_rate_limits is 'Atomic abuse-prevention windows for public Site Builder lead intake.';
