create extension if not exists pgcrypto;

create table if not exists public.lead_submissions (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 120),
  email text not null check (char_length(trim(email)) between 5 and 320),
  company text check (company is null or char_length(company) <= 160),
  message text not null check (char_length(trim(message)) between 2 and 4000),
  source text not null default 'site-builder' check (char_length(trim(source)) between 2 and 80),
  page_url text check (page_url is null or char_length(page_url) <= 2048),
  ip_address inet,
  user_agent text,
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'converted', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lead_submissions_business_created_idx on public.lead_submissions (business_id, created_at desc);
create index if not exists lead_submissions_business_status_idx on public.lead_submissions (business_id, status);

alter table public.lead_submissions enable row level security;

create or replace function public.touch_lead_submissions_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lead_submissions_touch_updated_at on public.lead_submissions;
create trigger lead_submissions_touch_updated_at
before update on public.lead_submissions
for each row execute function public.touch_lead_submissions_updated_at();

create policy lead_submissions_owner_select on public.lead_submissions
for select to authenticated
using (public.user_owns_business(business_id));

create policy lead_submissions_owner_update on public.lead_submissions
for update to authenticated
using (public.user_owns_business(business_id))
with check (public.user_owns_business(business_id));

create policy lead_submissions_owner_delete on public.lead_submissions
for delete to authenticated
using (public.user_owns_business(business_id));

comment on table public.lead_submissions is 'Inbound public lead forms generated by Site Builder pages; service role inserts, business owners read through RLS.';
