/**
 * ConversaPay Dashboard JavaScript
 * Core auth, subscription, business, product, integration, analytics and order flows.
 */
const API_BASE_URL = window.location.origin + '/api/v1';
let currentUser = null;
let currentBusiness = null;
let isDashboardInitialized = false;
let revenueChart = null;
let ordersChart = null;

window.addEventListener('error', (event) => { console.error('Dashboard error:', event.message); forceUnstickUI(event.message); });
window.addEventListener('unhandledrejection', (event) => { console.error('Dashboard rejection:', event.reason); forceUnstickUI(event.reason?.message || event.reason); });
const safetyNetTimer = setTimeout(() => { const overlay = document.getElementById('loadingOverlay'); if (overlay && !overlay.classList.contains('d-none')) forceUnstickUI('Loading timeout'); }, 8000);

function forceUnstickUI(reason) { console.error('Dashboard UI recovery:', reason); try { hideLoading(); } catch (_) {} const noBusiness = document.getElementById('noBusinessState'); const content = document.getElementById('dashboardContent'); if (noBusiness && content?.classList.contains('d-none')) noBusiness.classList.remove('d-none'); }
function showLoading() { document.getElementById('loadingOverlay')?.classList.remove('d-none'); }
function hideLoading() { document.getElementById('loadingOverlay')?.classList.add('d-none'); }
function token() { return window.ConversaPayAuth?.getToken?.() || localStorage.getItem('access_token') || localStorage.getItem('conversapay_auth_token') || sessionStorage.getItem('access_token') || sessionStorage.getItem('conversapay_auth_token'); }
function authHeaders() { const value = token(); return value ? { Authorization: `Bearer ${value}` } : {}; }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value ?? ''; return div.innerHTML; }

function checkAuthStatus() { const accessToken = token(); if (!accessToken) { hideLoading(); location.href = '/login.html'; return; } showLoading(); fetch(`${API_BASE_URL}/auth/me`, { headers: authHeaders() }).then((response) => { if (!response.ok) { window.ConversaPayAuth?.logout?.(); throw new Error('Authentication failed'); } return response.json(); }).then((data) => { currentUser = data; if (data.profile?.email_verified === false) { hideLoading(); document.getElementById('emailVerificationWall')?.classList.remove('d-none'); return; } return checkSubscriptionStatus(); }).catch((error) => { console.error(error); hideLoading(); if (error.message !== 'Authentication failed') location.href = '/login.html'; }); }

async function checkSubscriptionStatus() { window.userSubscriptionStatus = { isPro: false, planType: 'free' }; try { const response = await fetch(`${API_BASE_URL}/payments/profile`, { headers: authHeaders() }); if (response.ok) { const profile = await response.json(); const planType = String(profile.plan_type || 'free').toLowerCase(); window.userSubscriptionStatus = { isPro: ['pro', 'premium'].includes(planType), planType, subscriptionExpiresAt: profile.subscription_expires_at }; } } catch (error) { console.error('Subscription check failed:', error); } await loadUserBusinesses(); }
function getSubscriptionTier() { const status = window.userSubscriptionStatus || {}; const plan = String(status.planType || '').toLowerCase(); return plan === 'premium' ? 'premium' : (plan === 'pro' || status.isPro ? 'pro' : 'free'); }
function showUpgradeState() { document.getElementById('billing-upgrade-section')?.style && (document.getElementById('billing-upgrade-section').style.display = 'block'); document.getElementById('integrations-setup-section')?.style && (document.getElementById('integrations-setup-section').style.display = 'none'); ['upgradeState'].forEach((id) => document.getElementById(id)?.classList.remove('d-none')); ['noBusinessState','createBusinessFormCard','dashboardContent','proPlanBanner'].forEach((id) => document.getElementById(id)?.classList.add('d-none')); hideLoading(); }

async function handleUpgradeToPlan(planType, buttonEl) { const button = buttonEl || document.getElementById(planType === 'pro' ? 'upgradeToProBtn' : 'upgradeToPremiumBtn'); const original = button?.textContent || ''; if (button) { button.disabled = true; button.textContent = 'מפנה לתשלום...'; } try { const response = await fetch(`${API_BASE_URL}/payments/create-checkout-session`, { method: 'POST', headers: { ...authHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ user_id: currentUser?.user_id || currentUser?.id, email: currentUser?.email, full_name: currentUser?.full_name || '', plan_type: planType }) }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.url) throw new Error(data.detail || 'לא ניתן ליצור תשלום'); location.href = data.url; } catch (error) { console.error(error); alert(`שגיאה: ${error.message || 'נסה שוב'}`); if (button) { button.disabled = false; button.textContent = original; } } }
function handleLogout() { if (confirm('האם אתה בטוח שברצונך להתנתק?')) window.ConversaPayAuth?.logout?.() || (localStorage.clear(), sessionStorage.clear(), location.href = '/login.html'); }

async function loadUserBusinesses() { try { const response = await fetch(`${API_BASE_URL}/businesses`, { headers: authHeaders() }); const businesses = response.ok ? await response.json() : []; if (Array.isArray(businesses) && businesses.length) { currentBusiness = businesses[0]; showDashboardState(); } else showNoBusinessState(); } catch (error) { console.error(error); hideLoading(); showNoBusinessState(); } }
function showNoBusinessState() { const paid = window.userSubscriptionStatus?.isPro === true; const billing = document.getElementById('billing-upgrade-section'); const integrations = document.getElementById('integrations-setup-section'); if (billing) billing.style.display = paid ? 'none' : 'block'; if (integrations) integrations.style.display = paid ? 'block' : 'none'; document.getElementById('upgradeState')?.classList.toggle('d-none', paid); document.getElementById('noBusinessState')?.classList.toggle('d-none', !paid); document.getElementById('createBusinessFormCard')?.classList.add('d-none'); document.getElementById('dashboardContent')?.classList.add('d-none'); document.getElementById('proPlanBanner')?.classList.toggle('d-none', !paid); hideLoading(); }
function showCreateBusinessForm() { document.getElementById('noBusinessState')?.classList.add('d-none'); document.getElementById('createBusinessFormCard')?.classList.remove('d-none'); }
function hideCreateBusinessForm() { document.getElementById('createBusinessFormCard')?.classList.add('d-none'); document.getElementById('noBusinessState')?.classList.remove('d-none'); document.getElementById('createBusinessForm')?.reset(); }
async function handleCreateBusiness(event) { event.preventDefault(); const form = event.target; const button = form.querySelector('button[type="submit"]'); button.disabled = true; button.textContent = 'יוצר...'; try { const response = await fetch(`${API_BASE_URL}/businesses`, { method: 'POST', headers: { ...authHeaders(), 'Content-Type': 'application/json' }, body: JSON.stringify({ business_id: document.getElementById('businessId').value, business_name: document.getElementById('businessName').value, description: document.getElementById('businessDescription').value }) }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || 'יצירת העסק נכשלה'); currentBusiness = await response.json(); showDashboardState(); form.reset(); } catch (error) { alert(error.message); } finally { button.disabled = false; button.textContent = 'צור עסק'; } }

async function initDashboard() { if (isDashboardInitialized) return; isDashboardInitialized = true; const content = document.getElementById('dashboardContent'); try { content?.classList.remove('d-none'); if (currentBusiness) { window.currentBusinessId = currentBusiness.id; document.getElementById('businessDisplayName')?.replaceChildren(document.createTextNode(`🏢 ${currentBusiness.business_name}`)); document.getElementById('businessDisplaySlug')?.replaceChildren(document.createTextNode(`מזהה: ${currentBusiness.business_id}`)); document.dispatchEvent(new CustomEvent('conversapay:business-ready', { detail: { business_id: currentBusiness.id, business_name: currentBusiness.business_name } })); } await checkProStatusForIntegrations(); updateEmbedCode(); await loadAllData(); } catch (error) { console.error(error); } finally { hideLoading(); content?.classList.remove('d-none'); } }
function showDashboardState() { document.getElementById('billing-upgrade-section')?.style && (document.getElementById('billing-upgrade-section').style.display = 'none'); document.getElementById('integrations-setup-section')?.style && (document.getElementById('integrations-setup-section').style.display = 'block'); initDashboard().catch((error) => forceUnstickUI(error.message)); }
function applyLockOverlay(cardId, overlayId) { const card = document.getElementById(cardId); if (!card) return; document.getElementById(overlayId)?.remove(); const overlay = document.createElement('div'); overlay.id = overlayId; overlay.style.cssText = 'position:absolute;inset:0;background:rgba(15,23,42,.82);backdrop-filter:blur(5px);display:flex;flex-direction:column;align-items:center;justify-content:center;z-index:100;border-radius:12px;padding:30px;text-align:center;color:#f8fafc'; overlay.innerHTML = '<div style="font-size:4rem;margin-bottom:20px">🔒</div><h3 style="font-size:1.3rem;font-weight:700;color:#f8fafc;margin-bottom:12px">נעול, רכוש PRO או PREMIUM</h3><p style="color:#f8fafc;margin-bottom:24px;font-size:1rem">וקבל את האפשרויות האלה</p><div style="display:flex;gap:12px;flex-wrap:wrap;justify-content:center"><button onclick="handleUpgradeToPlan(\'pro\',this)" style="background:#2563eb;color:#fff;padding:14px 24px;font-weight:700;border-radius:8px;border:0;cursor:pointer">💳 שדרג ל-Pro</button><button onclick="handleUpgradeToPlan(\'premium\',this)" style="background:#6d28d9;color:#fff;padding:14px 24px;font-weight:700;border-radius:8px;border:0;cursor:pointer">👑 שדרג ל-Premium</button></div>'; if (getComputedStyle(card).position === 'static') card.style.position = 'relative'; card.style.overflow = 'hidden'; card.appendChild(overlay); }
function removeLockOverlay(id) { document.getElementById(id)?.remove(); }
async function checkProStatusForIntegrations() { try { const response = await fetch(`${API_BASE_URL}/payments/profile`, { headers: authHeaders() }); const profile = response.ok ? await response.json() : null; const paid = ['pro','premium'].includes(String(profile?.plan_type || '').toLowerCase()); window.userSubscriptionStatus = { isPro: paid, planType: profile?.plan_type || 'free' }; [{cardId:'integrationsCard',overlayId:'integrationLockOverlay'},{cardId:'ordersCard',overlayId:'ordersLockOverlay'},{cardId:'topProductsCard',overlayId:'topProductsLockOverlay'}].forEach(({cardId,overlayId}) => { removeLockOverlay(overlayId); if (!paid) applyLockOverlay(cardId,overlayId); }); const wa = document.getElementById('whatsappSection'); if (wa) { wa.classList.toggle('d-none', String(profile?.plan_type || '').toLowerCase() !== 'premium'); if (profile) loadWhatsAppSettings(profile); } } catch (error) { console.error(error); } }
async function checkUserPlan() {}
async function checkWebsiteStatus() { if (!currentBusiness) return; try { const response = await fetch(`${API_BASE_URL}/businesses/${currentBusiness.id}`, { headers: authHeaders() }); const business = response.ok ? await response.json() : {}; document.getElementById('websiteOnboardingCard')?.classList.toggle('d-none', Boolean(business.website_url)); } catch (_) { document.getElementById('websiteOnboardingCard')?.classList.add('d-none'); } }
function showOrdersSection() { const free = getSubscriptionTier() === 'free'; const section = document.querySelectorAll('.card')[2]; if (section) section.classList.toggle('d-none', false); if (free && section) section.setAttribute('data-locked', 'true'); }
function showWebsiteOnboarding() { document.getElementById('websiteOnboardingCard')?.classList.remove('d-none'); showOrdersSection(); }
function showStandardDashboard() { document.getElementById('websiteOnboardingCard')?.classList.add('d-none'); showOrdersSection(); }

function updateEmbedCode() { if (!currentBusiness) return; const node = document.getElementById('embedCodeSnippet'); if (node) node.textContent = `<!-- ConversaPay AI Chatbot -->\n<script>\n  window.ConversaPayWidgetConfig = { business_id: "${currentBusiness.id}" };\n</script>\n<script src="${window.location.origin}/frontend/js/widget.js" defer></script>`; }
function downloadWordPressPlugin() { if (!currentBusiness) return alert('נא ליצור עסק תחילה'); location.href = `/frontend/html/setup-guide.html?business_id=${currentBusiness.id}&tab=wordpress`; }
function copyEmbedCode() { if (!currentBusiness) return alert('נא ליצור עסק תחילה'); location.href = `/frontend/html/setup-guide.html?business_id=${currentBusiness.id}&tab=html`; }
async function loadAllData() { try { await Promise.all([loadProducts(), loadAnalytics()]); if (getSubscriptionTier() !== 'free') await loadOrders(); } catch (error) { console.error(error); } }

async function loadAnalytics() { if (!currentBusiness) return; try { const [analytics, revenue, orders] = await Promise.all([fetch(`${API_BASE_URL}/analytics/businesses/${currentBusiness.id}/analytics`,{headers:authHeaders()}).then(r=>r.ok?r.json():null),fetch(`${API_BASE_URL}/analytics/businesses/${currentBusiness.id}/revenue?days=${document.getElementById('analyticsPeriod')?.value||30}`,{headers:authHeaders()}).then(r=>r.ok?r.json():null),fetch(`${API_BASE_URL}/analytics/businesses/${currentBusiness.id}/orders?days=30`,{headers:authHeaders()}).then(r=>r.ok?r.json():null)]); if (analytics) updateKPICards(analytics); if (revenue) renderRevenueChart(revenue); if (orders) renderOrdersChart(orders); await loadTopProducts(); } catch (error) { console.error(error); } }
function updateKPICards(analytics) { const revenue = document.getElementById('kpiRevenue'); const conversion = document.getElementById('kpiConversion'); const aov = document.getElementById('kpiAOV'); const sessions = document.getElementById('kpiSessions'); if (revenue) revenue.textContent = `₪${Number(analytics?.total_revenue || 0).toFixed(2)}`; if (conversion) conversion.textContent = `${Number(analytics?.conversion_rate || 0).toFixed(1)}%`; if (aov) aov.textContent = `₪${Number(analytics?.average_order_value || 0).toFixed(2)}`; if (sessions) sessions.textContent = analytics?.unique_chat_sessions || 0; }
function renderRevenueChart(data) { const canvas = document.getElementById('revenueChart'); if (!canvas || typeof Chart === 'undefined') return; const rows = data?.revenue_by_day || []; revenueChart?.destroy(); revenueChart = new Chart(canvas.getContext('2d'), { type:'line', data:{labels:rows.map(x=>new Date(x.date).toLocaleDateString('he-IL',{month:'short',day:'numeric'})),datasets:[{data:rows.map(x=>x.revenue||0),borderColor:'#7c3aed',backgroundColor:'rgba(124,58,237,.12)',borderWidth:2,fill:true}]}, options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}} }); }
function renderOrdersChart(data) { const canvas = document.getElementById('ordersChart'); if (!canvas || typeof Chart === 'undefined') return; const values = data?.orders_by_status || {}; ordersChart?.destroy(); ordersChart = new Chart(canvas.getContext('2d'), { type:'bar', data:{labels:Object.keys(values).map(getStatusText),datasets:[{data:Object.values(values),backgroundColor:['#f59e0b','#10b981','#2563eb','#7c3aed','#b91c1c','#b91c1c']}]}, options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}} }); }
async function loadTopProducts() { if (!currentBusiness) return; try { const response = await fetch(`${API_BASE_URL}/analytics/businesses/${currentBusiness.id}/analytics`, { headers: authHeaders() }); if (response.ok) renderTopProducts((await response.json()).top_selling_products || []); } catch (error) { console.error(error); } }
function renderTopProducts(products) { const empty = document.getElementById('noProductsData'); const table = document.getElementById('topProductsTableContainer'); const body = document.getElementById('topProductsTableBody'); if (!empty || !table || !body) return; if (!products.length) { empty.classList.remove('d-none'); table.classList.add('d-none'); return; } empty.classList.add('d-none'); table.classList.remove('d-none'); body.innerHTML = products.map((product,index)=>`<tr><td><strong>${index+1}</strong></td><td><strong>${escapeHtml(product.name)}</strong></td><td><code>${escapeHtml(product.item_key)}</code></td><td><span class="badge badge-success">${product.total_quantity}</span></td><td>${product.order_count}</td></tr>`).join(''); }

async function loadOrders() { if (!currentBusiness?.id) return; try { const response = await fetch(`${API_BASE_URL}/orders?business_id=${encodeURIComponent(currentBusiness.id)}&limit=50`, { headers: authHeaders() }); if (response.ok) renderOrders(await response.json()); } catch (error) { console.error(error); } }
function renderOrders(orders) { const body=document.getElementById('ordersTableBody'); const empty=document.getElementById('noOrders'); const table=document.getElementById('ordersTableContainer'); if(!body||!empty||!table)return; if(!orders?.length){empty.classList.remove('d-none');table.classList.add('d-none');return;} empty.classList.add('d-none');table.classList.remove('d-none');body.innerHTML=orders.map((order,index)=>`<tr><td>${index+1}</td><td><code>${escapeHtml(order.order_number||order.id||'N/A')}</code></td><td><strong>${escapeHtml(order.customer_info?.name||order.customer_info?.email||'לקוח אנונימי')}</strong></td><td>${escapeHtml(order.status||'pending')}</td><td><strong>₪${Number(order.total||0).toFixed(2)}</strong></td><td>${new Date(order.created_at).toLocaleDateString('he-IL')}</td><td><button class="btn btn-sm btn-outline" onclick="viewOrderDetails('${order.id}')">👁️ פרטים</button></td></tr>`).join(''); }
async function viewOrderDetails(orderId) { if (!currentBusiness || !orderId) return; const response = await fetch(`${API_BASE_URL}/orders/${orderId}`, { headers: authHeaders() }); if (!response.ok) return alert('שגיאה בטעינת פרטי ההזמנה'); const order = await response.json(); alert(`📋 פרטי הזמנה\nמספר: ${order.order_number}\nלקוח: ${order.customer_info?.name || order.customer_info?.email || 'לקוח אנונימי'}\nסטטוס: ${getStatusText(order.status)}\nסכום: ₪${Number(order.total||0).toFixed(2)}`); }
function getStatusBadgeClass(status) { return ({pending:'warning',paid:'success',processing:'info',shipped:'primary',delivered:'success',canceled:'danger',refunded:'danger',failed:'danger'})[status] || 'secondary'; }
function getStatusText(status) { return ({pending:'ממתין לתשלום',paid:'שולם ✓',processing:'בטיפול',shipped:'נשלח',delivered:'נמסר',canceled:'בוטל',refunded:'הוחזר',failed:'נכשל'})[status] || status || ''; }

function showAddProductForm() { document.getElementById('productFormContainer')?.classList.remove('d-none'); document.getElementById('productFormTitle') && (document.getElementById('productFormTitle').textContent='הוסף מוצר חדש'); document.getElementById('productForm')?.reset(); document.getElementById('productId') && (document.getElementById('productId').value=''); }
function hideProductForm() { document.getElementById('productFormContainer')?.classList.add('d-none'); }
async function handleSaveProduct(event) { event.preventDefault(); if (!currentBusiness) return alert('נא לבחור עסק תחילה'); const button=event.target.querySelector('button[type="submit"]'); button.disabled=true; try { const id=document.getElementById('productId').value; const payload={business_id:currentBusiness.id,item_key:document.getElementById('productItemKey').value,name:document.getElementById('productName').value,description:document.getElementById('productDescription').value||null,price:Number(document.getElementById('productPrice').value),image_url:document.getElementById('productImageUrl').value||null,is_active:document.getElementById('productIsActive').checked,payment_link:document.getElementById('productPaymentLink').value.trim()||null}; const response=await fetch(id?`${API_BASE_URL}/products/${id}`:`${API_BASE_URL}/products`,{method:id?'PUT':'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(payload)}); if(!response.ok)throw new Error((await response.json().catch(()=>({}))).detail||'שמירת המוצר נכשלה'); hideProductForm(); loadProducts(); } catch(error){alert(error.message)} finally{button.disabled=false;} }
async function loadProducts() { if(!currentBusiness) return; try { const response=await fetch(`${API_BASE_URL}/products?business_id=${currentBusiness.id}&active_only=false`,{headers:authHeaders()}); if(!response.ok)return; const products=await response.json(); const empty=document.getElementById('noProducts'); const grid=document.getElementById('productsGrid'); if(!empty||!grid)return; empty.classList.toggle('d-none',products.length>0); grid.classList.toggle('d-none',products.length===0); grid.innerHTML=products.map(product=>`<article class="card"><strong>${escapeHtml(product.name)}</strong><code>${escapeHtml(product.item_key)}</code><span>₪${Number(product.price||0).toFixed(2)}</span></article>`).join(''); } catch(error){console.error(error)} }
async function editProduct(productId) { const response=await fetch(`${API_BASE_URL}/products/${productId}`,{headers:authHeaders()}); if(!response.ok)return; const product=await response.json(); ['productId','productItemKey','productName','productDescription','productPrice','productImageUrl','productPaymentLink'].forEach((id)=>{const key=id.replace('product','').replace(/^./,m=>m.toLowerCase()); const el=document.getElementById(id); if(el) el.value=product[id==='productId'?'id':id==='productItemKey'?'item_key':id==='productName'?'name':id==='productDescription'?'description':id==='productPrice'?'price':id==='productImageUrl'?'image_url':'payment_link']||'';}); document.getElementById('productFormContainer')?.classList.remove('d-none'); }
async function deleteProduct(productId) { if(!confirm('האם אתה בטוח שברצונך למחוק מוצר זה?'))return; const response=await fetch(`${API_BASE_URL}/products/${productId}`,{method:'DELETE',headers:authHeaders()}); if(response.ok)loadProducts(); }

function loadWhatsAppSettings(profile) { if(!profile)return; const map={waPhoneNumberId:'whatsapp_phone_number_id',waAccessToken:'whatsapp_access_token',waVerifyToken:'whatsapp_verify_token'}; Object.entries(map).forEach(([id,key])=>{const el=document.getElementById(id);if(el)el.value=profile[key]||''}); if(profile.whatsapp_verify_token)showWebhookUrl(profile.whatsapp_verify_token); }
function showWebhookUrl() { const el=document.getElementById('waWebhookUrl'); if(el){el.textContent=`Webhook URL: ${window.location.origin}/api/v1/whatsapp/webhook`;el.style.display='block';document.getElementById('waCopyWebhook')?.style && (document.getElementById('waCopyWebhook').style.display='inline-flex');} }
async function copyWebhookUrl() { await navigator.clipboard?.writeText(`${window.location.origin}/api/v1/whatsapp/webhook`).catch(()=>{}); const button=document.getElementById('waCopyWebhook'); if(button){button.textContent='✓ הועתק!';setTimeout(()=>button.textContent='📋 העתק Webhook URL',2000);} }
async function handleSaveWhatsApp(event) { event.preventDefault(); const fields=['waPhoneNumberId','waAccessToken','waVerifyToken'].map(id=>document.getElementById(id)?.value.trim()); if(fields.some(Boolean=>!Boolean))return; const response=await fetch(`${API_BASE_URL}/auth/whatsapp-settings`,{method:'PUT',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({whatsapp_phone_number_id:fields[0],whatsapp_access_token:fields[1],whatsapp_verify_token:fields[2]})}); const status=document.getElementById('waStatus'); if(status){status.style.display='block';status.textContent=response.ok?'✅ הגדרות WhatsApp נשמרו בהצלחה!':'שגיאה בשמירת ההגדרות';} }

document.addEventListener('DOMContentLoaded', () => { console.log('Dashboard loaded'); initializeEventListeners(); checkAuthStatus(); });
function initializeEventListeners() { document.getElementById('logoutBtn')?.addEventListener('click', handleLogout); document.getElementById('upgradeToProBtn')?.addEventListener('click', () => handleUpgradeToPlan('pro')); document.getElementById('upgradeToPremiumBtn')?.addEventListener('click', () => handleUpgradeToPlan('premium')); document.getElementById('showCreateFromEmpty')?.addEventListener('click', showCreateBusinessForm); document.getElementById('cancelCreateBusiness')?.addEventListener('click', hideCreateBusinessForm); document.getElementById('createBusinessForm')?.addEventListener('submit', handleCreateBusiness); document.getElementById('addProductBtn')?.addEventListener('click', showAddProductForm); document.getElementById('cancelProductBtn')?.addEventListener('click', hideProductForm); document.getElementById('productForm')?.addEventListener('submit', handleSaveProduct); document.getElementById('downloadWordPressPlugin')?.addEventListener('click', downloadWordPressPlugin); document.getElementById('copyEmbedCode')?.addEventListener('click', copyEmbedCode); document.getElementById('whatsappForm')?.addEventListener('submit', handleSaveWhatsApp); document.getElementById('waCopyWebhook')?.addEventListener('click', copyWebhookUrl); }
setInterval(() => { if(currentBusiness && token())loadOrders(); }, 30000);
